// Static site generator. Reads content/ and writes plain HTML into the project
// root, which stays directly deployable on any host.
//
//   node tools/build-site.mjs
//
// Every page ends up at <route>/index.html so clean URLs work without host
// specific rewrite rules. The homepage is the one exception, at ./index.html.
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join as joinPath } from 'node:path'
import YAML from 'yaml'
import { layout } from '../templates/layout.mjs'
import { renderBlocks } from '../templates/blocks.mjs'
import { insightPage, jobPage } from '../templates/pages.mjs'

const CONTENT = 'content'
const BANNER = '<!-- Generated by tools/build-site.mjs from content/. Do not edit by hand. -->\n'

/* ------------------------------------------------------------ frontmatter --- */

function readDoc(file) {
  const raw = readFileSync(file, 'utf8').replace(/^﻿/, '')
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw)
  if (!m) throw new Error(`${file}: missing --- frontmatter block`)
  const data = YAML.parse(m[1]) ?? {}
  return { ...data, body: m[2].trim(), file }
}

const listDir = (dir) => {
  try {
    return readdirSync(dir)
      .filter((n) => n.endsWith('.md'))
      .map((n) => ({ slug: n.replace(/\.md$/, ''), doc: readDoc(`${dir}/${n}`) }))
  } catch {
    return []
  }
}

/* ---------------------------------------------------------------- helpers --- */

const DATE_FMT = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

const dateLabel = (iso) => DATE_FMT.format(new Date(iso + 'T12:00:00Z'))

function write(route, html) {
  const out = route === '/' ? 'index.html' : joinPath(route.replace(/^\//, ''), 'index.html')
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, BANNER + html)
  return out
}

/* ---------------------------------------------------------------- content --- */

const site = YAML.parse(readFileSync(`${CONTENT}/site.yml`, 'utf8'))

const articles = listDir(`${CONTENT}/insights/articles`).map(({ slug, doc }) => ({
  ...doc,
  slug,
  kind: 'Articles',
  kindLabel: 'Articles',
  href: `/insights/${slug}`,
  dateLabel: dateLabel(doc.date),
}))

const projects = listDir(`${CONTENT}/insights/projects`).map(({ slug, doc }) => ({
  ...doc,
  slug,
  kind: 'Projects',
  kindLabel: 'Projects',
  href: `/insights/${slug}`,
  dateLabel: dateLabel(doc.date),
}))

const insights = [...articles, ...projects].sort((a, b) => (a.date < b.date ? 1 : -1))

const jobs = listDir(`${CONTENT}/jobs`).map(({ slug, doc }) => ({
  ...doc,
  slug,
  href: `/careers/${slug}`,
}))

const bySlug = Object.fromEntries(insights.map((i) => [i.slug, i]))

const ctx = { site, insights, articles, projects, jobs, bySlug }

/**
 * A block of `{ type: include, name: x }` splices in content/partials/x.yml.
 * Several pages share whole sections word for word, and duplicating them across
 * six content files would guarantee they drift apart.
 */
function expand(blocks = []) {
  return blocks.flatMap((b) => {
    if (b.type !== 'include') return [b]
    const partial = YAML.parse(readFileSync(`${CONTENT}/partials/${b.name}.yml`, 'utf8'))
    return expand(partial.blocks ?? []).map((inner) => ({ ...inner, ...(b.overrides ?? {}) }))
  })
}

/* ----------------------------------------------------------------- render --- */

const written = []

function emit(route, doc, content, headMode = 'paper') {
  written.push(
    write(
      route,
      layout({
        title: doc.title ?? site.seo.titleSuffix,
        description: doc.description,
        path: route,
        headMode,
        content,
        site,
      })
    )
  )
}

/* Pages carrying `draft: true` stay in content/ but are not published: no HTML is
   written and they stay out of the sitemap. Removing the flag brings the page
   back exactly as it was, which is why taking one down is a one line change here
   rather than a deleted file. Whoever takes one down also has to remove its entry
   from `nav` in site.yml, or the header links into nothing. */
const drafts = []

// Composed pages: content/pages, content/solutions, content/services.
for (const dir of ['pages', 'solutions', 'services']) {
  for (const { slug, doc } of listDir(`${CONTENT}/${dir}`)) {
    const route = doc.route ?? (dir === 'pages' ? (slug === 'home' ? '/' : `/${slug}`) : `/${dir}/${slug}`)
    if (doc.draft) {
      drafts.push(route)
      /* An earlier build may have published it. Leaving that file behind would
         keep the page reachable by URL while nothing links to it. */
      rmSync(route.replace(/^\//, ''), { recursive: true, force: true })
      continue
    }
    const blocks = expand(doc.blocks)
    const first = blocks[0]
    const headMode =
      doc.headMode ?? (first?.type === 'heroVideo' || first?.tone === 'void' ? 'over' : 'paper')
    emit(route, doc, renderBlocks(blocks, ctx), headMode)
  }
}

// Detail pages.
for (const item of insights) emit(item.href, item, insightPage(item, ctx))
for (const item of jobs) emit(item.href, item, jobPage(item, ctx))

/* ---------------------------------------------------------------- sitemap --- */

const routes = written.map((f) =>
  f === 'index.html' ? '/' : '/' + f.replace(/\\/g, '/').replace(/\/index\.html$/, '')
)

const urls = routes
  .sort()
  .map((r) => `  <url><loc>${site.seo.origin}${r}</loc></url>`)
  .join('\n')

writeFileSync(
  'sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
)

writeFileSync('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${site.seo.origin}/sitemap.xml\n`)

console.log(`${written.length} pages written`)
console.log(routes.sort().map((r) => '  ' + r).join('\n'))
if (drafts.length) {
  console.log(`\n${drafts.length} draft, not published:`)
  console.log(drafts.sort().map((r) => '  ' + r).join('\n'))
}
